### ISSUE TITLE
可以增加一个用户最近“动态”的获取吗

### ISSUE THREAD

**Issue by dick318** [AlexTan-b-z/ZhihuSpider#5]
有的用户虽然没有提问，或者回答问题， 但是会有点赞和关注了某些话题.

在用户主页有一个“动态”
链接是类似这样的
https://www.zhihu.com/api/v4/members/yang-da-yi-19/activities?limit=20&after_id=1503246015&desktop=True

这类用户也是值得分析的

**Comment by AlexTan-b-z** [comment]
哦哦，明白，动态暂时没有抓，如果有需要的话，后续我会补上去...也比较简单，多加一个动态Item，spider里多写一个函数就可以了。

**Comment by dick318** [comment]
可以加一个开关，可选需要爬取哪些内容(如提问，回答，文章，动态)，有的时候并不需要全部的数据，另外动态有时间麻烦加一下 O(∩_∩)O谢谢

**Comment by AlexTan-b-z** [comment]
恩恩,没问题，谢谢你的建议！

**Comment by kxzhot** [comment]
好想知道如何爬这个豆瓣全站图书的基本信息，抓了三百多数据之后就403爬不了了。https://book.douban.com/tag/
